---
title: '2019-06-12'
author: "林茂廷"
date: "6/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
load(url("https://www.dropbox.com/s/duh5aaqgl2f5m3z/loopTranscriptData.Rda?raw=1"))
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
studentIds5 <- studentIds[1:5] # 前5筆學號
```


```{r}
for(i in studentIds5){ 
  print(i) 
}
```

```{r}
for(i in c(1:5)){ 
  print(i) 
}
```


```{r}
for(i in c(1:5)){ 
  print(studentIds5[[i]]) 
}
```


```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```

```{r}
i <- 1
print(studentIds5[[i]])
```

```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```

```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```


```{r}
library(stringr)
for(i in seq_along(gmailAddress)){
  if (str_detect(gmailAddress[[i]],"@gmail.com")){
    print(gmailAddress[[i]])}
  else{
    print(str_c(gmailAddress[[i]],"@gmail.com"))
  }

}
```

```{r}
for(i in seq_along(gmailAddress)){
  if(!(str_detect(gmailAddress[[i]],"@gmali.com"))){
    gmailAddress[[i]] <- str_c(gmailAddress[[i]],"@gmali.com")
  }
}

gmailAddress
```


```{r}
# 開始設定
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
cat("起始狀況\n")
gmailAddress

# for loop
for(i in seq_along(gmailAddress)){
  if(!str_detect(gmailAddress[[i]],"@gmail.com")){
    correctGmailAddress <-
      str_c(gmailAddress[[i]],"@gmail.com")
    gmailAddress[[i]] <- correctGmailAddress
  }
}

cat("修正後狀況\n")
gmailAddress
```

```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```

```{r}
commitHistory$
```


```{r}
for (i in seq_along(commitHistory)){
  print(commitHistory[[i]]$commit$author$name)
}
```

```{r}
for (i in seq_along(commitHistory)){
  print(
    str_c(
    "Author is ",
    commitHistory[[i]]$commit$author$name,
    ". Committer is",
    commitHistory[[i]]$commit$committer$name
    )
  )
}
```

```{r}
for (i in seq_along(commitHistory)){
  print(commitHistory[[i]]$commit$author$name == commitHistory[[i]]$commit$committer$name)
}
```






