---
title: '2019-06-05'
author: "林茂廷"
date: "05/06/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha=0.5,.beta=0.5){
  utilValue <- x^.alpha*y^.beta
  return(utilValue)
}
```


```{r}
utility_cobb_douglass(1,2,0.5,0.8)
```


```{r}
utility_cobb_douglass(1,2,0.5,0.8)
```


```{r}
load(url("https://github.com/tpemartin/github-data/blob/master/loopTranscriptData.Rda?raw=true"))
```


```{r}
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
```


```{r}
studentIds5 <- studentIds[1:5] #以前五筆作為sequence_source
studentIds5
```


#作法一
```{r}
for(i in studentIds5){
  print(i) # 印出studentIds5[[i]]
}
```


```{r}
gpa_fun(studentID[[1]])
for(i in studentIds5){
  print(i) 
  print(gpa_fun(i))
}
```


```{r}
for(i in c(1:5)){
  print(i) 
}
```


```{r}
for(i in c(1:5)){
  print(i) 
  print(studentIds5[[i]])
}
```


```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```


```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```


```{r}
library(stringr)
for(i in seq_along(gmailAddress)){
  if (str_detect(gmailAddress[[i]],"@gmail.com")){
    print(gmailAddress[[i]])}
  else{
    print(str_c(gmailAddress[[i]],"@gmail.com"))
  }
  
}
```


```{r}
EconCourseSelectionInfo <- list(
  "101"=list(
    url="http://www.econ.ntpu.edu.tw/econ/files/Way/2016072195021.doc"),
  "104"=list(
    url="http://www.econ.ntpu.edu.tw/econ/files/Way/2016072195041.doc"),
  "105"=list(
    url="http://www.econ.ntpu.edu.tw/econ/files/Way/20170516144353.doc"),
  "107"=list(
    url="http://www.econ.ntpu.edu.tw/econ/files/Way/20180518121643.pdf")
)
EconCourseSelectionInfo
```


```{r}
search_courseRules <- function(entranceYear,EconCourseSelectionInfo){
  year1 <- as.integer(entranceYear)
  if(year1 >= "101" & year1 < "104" ){
    output <- EconCourseSelectionInfo[["101"]]$url
  }else if(year1 >= "104" & year1 < "105"){
    output <- EconCourseSelectionInfo[["104"]]$url
  }else if(year1 >= "105" & year1 < "107"){
    output <- EconCourseSelectionInfo[["105"]]$url
  }else if(year1 >= "107"){
    output <- EconCourseSelectionInfo[["107"]]$url
  }else{
    output <- "很抱歉沒有您入學年的資訊，請打系辦電話"
  }
  rerurn (output)
}
search_courseRules
```


```{r}
search_courseRules_flexible <- function(entranceYear,courseSelectionInfo){
  as.numeric(entranceYear) -> year2
  as.numeric(names(courseSelectionInfo)) -> year3
  loginum <- year2 >= year3
  if(any(loginum)){
    num1 <- max(year3[loginum])
    output <- courseSelectionInfo[[num1]]$url
  }else{
    output <- "很抱歉沒有您入學年的資訊，請打系辦電話"
  }
  return(output)
}
```




