---
title: '2019-05-08'
author: "林茂廷"
date: "5/8/2019"
output: html_document
---

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Vector1[["名稱4"]]
```

#colnames/rownames

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2)
names(StuDF2)
```

```{r}
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
StuDF2
```

#只改col2的名稱

```{r}
colnames(StuDF2)[[2]] <- c("姓名")
colnames(StuDF2)
StuDF2
```

#改col2 col3的名稱

```{r}
colnames(StuDF2)[c(2,3)] <- c("name","grade")
colnames(StuDF2)
StuDF2
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
colnames(StuDF)[c(1,2,3)] <- c("StudentID","name","grade")
colnames(StuDF)
StuDF
```

```{r}
library(stringr)
rownames(StuDF2)
rownames(StuDF2)[c(1,2,3)] <- c("StudentID","name","grade")
rownames(StuDF2)
StuDF2
```

#新增取代

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
```

```{r}
b[[3]] <- FALSE
b[[5]] <- "7"
b
```

```{r}
b$元素3 <- TRUE
b
```

```{r}
b[["元素3"]] <- FALSE
b
```

```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```

```{r}
library(lubridate)
time3<- exData3$期間
time3<- ymd(time3)
time3-> exData3$期間
class(exData3$期間)
```

```{r}
exData3$isAsiaCrisis <- exData3$期間 >= ymd("1997-06-01") & exData3$期間 <= ymd("1998-12-01")
class(exData3$isAsiaCrisis)
```

```{r}
logiAsiaCrisis <- 
exData3[logiAsiaCrisis, ]
```

```{r}
exData3[exData3$isAsiaCrisis == T , ]
exData3[exData3$isAsiaCrisis, ]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
names(transcriptDataFinal)
```

```{r}
transcriptDataFinal[transcriptDataFinal$學號 == "92aS67fee",]
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
class(utility_cobb_douglass)
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8)
```

```{r}
abc <- function(x,.alpha){
  abcd <- x+.alpha
  return(abcd)
}
```

```{r}
abc(5,3)
```

```{r}
supply_fun <- function(a,b,P){
Qs <- a+b*P 
  return(Qs) 
}
demand_fun <- function(c,d,P){
Qd <- c-d*P 
  return(Qd) 
}
```

```{r}
supply_fun(0,1,1)
demand_fun(5,1,1)
f <- demand_fun(5,1,1) - supply_fun(0,1,1)
f
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent
sum(transcriptDataFinal$學期成績[logiChosenStudent]*
  transcriptDataFinal$學分數[logiChosenStudent])/
  sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
```

```{r}
subSample <- transcriptDataFinal[logiChosenStudent,]
sum(subSample$學期成績*subSample$學分數)/
  sum(subSample$學分數) -> GPA
```

```{r}
gpa_fun <- function(studentID){
transcriptDataFinal$學號==studentID -> logiChosenStudent
  subSample <- transcriptDataFinal[logiChosenStudent,]
sum(subSample$學期成績*subSample$學分數)/
  sum(subSample$學分數) -> GPA
  return(GPA) 
}
```

```{r}
gpa_fun("223S63286")
gpa_fun("105S60ba1")
```

