---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```
```{r}
x3 == y3
```
```{r}
x3 != y3
```
```{r}
x3 == y3
!(x3 == y3)
```
```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```
```{r}
head(currency)
```

```{r}
class(currency)
```
```{r}
currency <- as.factor(currency)
class(currency)
```
```{r}
levels(currency)
```
```{r}
length(levels(currency))
```
```{r}
step1_extractlevelsVector <- levels(currency)
step1_extractlevelsVector
```
```{r}
step2_countVectorLength <- length(step1_extractlevelsVector)
```

```{r}
step2_countVectorLength
```
```{r}
head(currency)
levels(currency)
```
```{r}
currency2 <- c("日元","美元","日元")
currency2
```
```{r}
currency2 == "日元"
```
```{r}
sum(currency2 == "日元")
```
```{r}
head(currency)
sum(currency == "日圓JPY/USD")
```
# 5.4 Logical Operators
```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
!(x5 %in% greatTaipei)
```
```{r}
y5 <- c("女","男","女")

y5=="女"
!(y5=="女")
```
```{r}
x5 %in% greatTaipei
y5=="女"
(x5 %in% greatTaipei) & (y5=="女")
```
```{r}
which((x5 %in% greatTaipei) & (y5=="女"))
```
```{r}
x5
y5
```
```{r}
(x5 %in% greatTaipei)
(y5=="女") 
(x5 %in% greatTaipei) | (y5=="女")
```
```{r}
which(y5=="女")
which((x5 %in% greatTaipei) | (y5=="女"))
```
```{r}
x5 %in% greatTaipei
y5=="女"
xor(x5 %in% greatTaipei, y5=="女")
```
```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```
```{r}
class(date)
```
```{r}
head(date)
```
```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```
```{r}
class(date)
```
```{r}
isAfter19800801 <-
  date >= ymd("1980-08-01")
```

```{r}
head(as.integer(date))
as.integer(ymd("1980-08-01"))
head(date >= ymd("1980-08-01"))
```
```{r}
class(isAfter19800801)
```
```{r}
sum(isAfter19800801)
```
```{r}
head(currency)
```
```{r}
head(currency == "歐元USD/EUR")

isEURO <- currency == "歐元USD/EUR"
```

```{r}
sum(isEURO)
```
```{r}
currency <- as.factor(currency)
```

```{r}
isEURO <- currency == "歐元USD/EUR"
sum(isEURO)
```
```{r}
isExchangeRateNA <-
  is.na(exchangeRate)
sum(isExchangeRateNA)
```
```{r}
isNotNA <- !is.na(exchangeRate)
isEURO <- currency == "歐元USD/EUR"
```
```{r}
satisfyBoth <- isNotNA & isEURO
sum(satisfyBoth)
```
```{r}
satisfyBoth <- !is.na(exchangeRate) & currency == "歐元USD/EUR"
sum(satisfyBoth)
```
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`必選修類別（必∕選∕通）`
major <- transcriptDataFinal$學系
studentID <- transcriptDataFinal$學號
grade <- transcriptDataFinal$學期成績
```
```{r}
sum(major == "經濟學系")
```
```{r}
sum(studentID == "5bdS6977b")
```
```{r}
sum(studentID == "5bdS6977b" & grade >= 60)
```
```{r}
sum(major == "經濟學系" & courseType == "選")
```
```{r}
student <- major == "經濟學系" & courseType == "必"
prenctage <- student & grade < 60
sum(prenctage)/sum(student)
```


